name: Build RINASim and execute examples
on: [push]

jobs:
  build:
    name: "Build and run examples"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download latest image
        run: scripts/tests/do_in_docker date
      - name: Build project
        run: scripts/tests/do_in_docker scripts/tests/build
      - name: Test project
        run: scripts/tests/do_in_docker scripts/tests/run_examples

